# Generated by Django 5.2.3 on 2025-10-05 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0006_alter_offerdetail_price'),
        ('orders_app', '0004_remove_order_user_alter_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='business_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offerer', to='offers_app.offer'),
        ),
    ]
