# Generated by Django 5.2.3 on 2025-10-09 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0006_alter_offerdetail_price'),
        ('orders_app', '0006_alter_order_business_user_alter_order_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='business_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerer', to='offers_app.offer'),
        ),
    ]
