# Generated by Django 5.2.3 on 2025-09-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_type',
            field=models.CharField(blank=True, choices=[('customer', 'Customer'), ('business', 'Business')], max_length=10, null=True),
        ),
    ]
