# Generated by Django 5.2.3 on 2025-08-18 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='type',
            new_name='user_type',
        ),
    ]
