# Generated by Django 5.2.3 on 2025-09-29 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_account_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='business_user',
        ),
        migrations.RemoveField(
            model_name='account',
            name='customer_user',
        ),
    ]
