# Generated by Django 5.2.3 on 2025-08-31 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_rename_type_account_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='business_user',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='account',
            name='customer_user',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
