# Generated by Django 5.2.3 on 2025-10-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='business_user',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='offer_images/'),
        ),
    ]
