# Generated by Django 5.2.3 on 2025-10-01 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0002_alter_offer_business_user_alter_offer_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='business_user',
        ),
    ]
