# Generated by Django 5.2.3 on 2025-10-01 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0003_remove_offer_business_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='business_user',
            field=models.PositiveIntegerField(default=5, editable=False),
            preserve_default=False,
        ),
    ]
