# Generated by Django 5.2.3 on 2025-09-23 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0002_alter_account_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('description', models.TextField(blank=True, default='')),
                ('file', models.FileField(blank=True, null=True, upload_to='profiles/')),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('tel', models.CharField(blank=True, default='', max_length=20)),
                ('working_hours', models.CharField(blank=True, default='', max_length=128)),
            ],
        ),
    ]
