# Generated by Django 5.2.3 on 2025-08-26 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='file',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tel',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='working_hours',
        ),
    ]
