# Generated by Django 5.2.3 on 2025-08-26 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0002_remove_profile_created_at_remove_profile_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='description',
        ),
    ]
