# Generated by Django 5.2.3 on 2025-08-26 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0004_profiles_delete_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiles',
            old_name='user',
            new_name='account',
        ),
    ]
