# Generated by Django 5.2.3 on 2025-08-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0007_remove_profiles_id_alter_profiles_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
