# Generated by Django 5.2.3 on 2025-08-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0008_alter_profiles_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='profiles',
            name='tel',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='profiles',
            name='type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profiles',
            name='working_hours',
            field=models.CharField(default='', max_length=128),
        ),
    ]
