# Generated by Django 5.2.3 on 2025-08-26 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0009_profiles_location_profiles_tel_profiles_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='type',
        ),
    ]
