# Generated by Django 5.2.3 on 2025-08-27 08:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0010_remove_profiles_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileUpload',
        ),
        migrations.AddField(
            model_name='profiles',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/profiles/'),
        ),
        migrations.AddField(
            model_name='profiles',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 8, 27, 8, 17, 13, 123474, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profiles',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='tel',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='working_hours',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
