# Generated by Django 5.2.3 on 2025-08-27 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0011_delete_fileupload_profiles_file_profiles_uploaded_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='uploaded_at',
        ),
    ]
